name: Test, Build and Push to Google Cloud run
on: 
    workflow_dispatch: # this means that the workflow can be triggered manually
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
        - master
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                python-version: 3.8
            - name: Install requirements
              run: pip install -r requirements.txt 
            - name: Run tests
              run: pytest src/tests.py
    build_deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up QUEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build container image
          run: docker build -t serveless-py .
